# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Design2.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QButtonGroup

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1277, 717)
        MainWindow.showFullScreen()
        MainWindow.setStyleSheet("background-color: rgb(24,42,60);\n"
"color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.quit_button = QtWidgets.QPushButton(self.centralwidget)
        self.quit_button.setGeometry(QtCore.QRect(1130, 0, 140, 35))
        self.quit_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.quit_button.setStyleSheet("QPushButton {\n"
"                    font: 10pt \"Rockwell\";\n"
"                      padding: 5px;\n"
"                         color: rgb(42, 66, 79);\n"
"                     background-color: rgb(255, 255, 255);\n"
"                      border-bottom: 2px solid transparent;\n"
"                      border-radius:8px;\n"
"                        }")
        self.quit_button.setObjectName("quit_button")
        self.title_label = QtWidgets.QLabel(self.centralwidget)
        self.title_label.setGeometry(QtCore.QRect(100, 1, 160, 40))
        self.title_label.setStyleSheet("QLabel{\n"
"    font: 15pt \"Rockwell\";\n"
"    border: 1px solid white;\n"
"\n"
"}")
        self.title_label.setScaledContents(False)
        self.title_label.setAlignment(QtCore.Qt.AlignCenter)
        self.title_label.setObjectName("title_label")
        self.title_image = QtWidgets.QLabel(self.centralwidget)
        self.title_image.setGeometry(QtCore.QRect(0, 0, 91, 41))
        self.title_image.setStyleSheet("")
        self.title_image.setText("")
        self.title_image.setPixmap(QtGui.QPixmap("src/fourier.jpg"))
        self.title_image.setScaledContents(True)
        self.title_image.setObjectName("title_image")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 40, 1011, 631))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.view_port_4 = QtWidgets.QGroupBox(self.layoutWidget)
        self.view_port_4.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.view_port_4.setObjectName("view_port_4")
        self.comp_selection_4 = QtWidgets.QComboBox(self.view_port_4)
        self.comp_selection_4.setGeometry(QtCore.QRect(310, 270, 161, 21))
        self.comp_selection_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comp_selection_4.setStyleSheet("QComboBox{\n"
"            font: 12pt \"Modern No. 20\";\n"
"            color: white;\n"
"            background-color: rgb(24,42,60);\n"
"            border: 1px solid white;\n"
"            border-radius:8px;\n"
"                        }")
        self.comp_selection_4.setObjectName("comp_selection_4")
        self.comp_selection_4.addItem("")
        self.horizontalSlider_4 = QtWidgets.QSlider(self.view_port_4)
        self.horizontalSlider_4.setGeometry(QtCore.QRect(100, 270, 201, 20))
        self.horizontalSlider_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.horizontalSlider_4.setStyleSheet("QSlider::handle:horizontal {\n"
"        background: #00aaff;  /* Blue handle */\n"
"        border: 2px solid #005f87;  /* Darker border for contrast */\n"
"        margin: -10px 0;  /* Adjust to center the handle on the groove */\n"
"        border-radius: 6px;\n"
"    }")
        self.horizontalSlider_4.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_4.setObjectName("horizontalSlider_4")
        self.horizontalSlider_4.setRange(0,100)
        self.input_image_4 = QtWidgets.QLabel(self.view_port_4)
        self.input_image_4.setGeometry(QtCore.QRect(10, 20, 270, 240))
        self.input_image_4.setStyleSheet("QLabel {\n"
"                          color: rgb(42, 66, 79);\n"
"                       border-bottom: 2px solid transparent;\n"
"                      background-color: rgb(255, 255, 255);\n"
"                       border-radius:10px;\n"
"                      border: 1px solid black;\n"
"                        }")
        self.input_image_4.setText("")
        self.input_image_4.setObjectName("input_image_4")
        self.FT_components_4 = QtWidgets.QLabel(self.view_port_4)
        self.FT_components_4.setGeometry(QtCore.QRect(290, 20, 200, 240))
        self.FT_components_4.setStyleSheet("QLabel {\n"
"                          color: rgb(42, 66, 79);\n"
"                      background-color: rgb(255, 255, 255);\n"
"                       border-radius:10px;\n"
"                        }")
        self.FT_components_4.setText("")
        self.FT_components_4.setObjectName("FT_components_4")
        self.reset_button_4 = QtWidgets.QPushButton(self.view_port_4)
        self.reset_button_4.setGeometry(QtCore.QRect(10, 270, 84, 25))
        self.reset_button_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.reset_button_4.setStyleSheet("QPushButton {\n"
"                    font: 10pt \"Rockwell\";\n"
"                      padding: 5px;\n"
"                         color: rgb(42, 66, 79);\n"
"                     background-color: rgb(255, 255, 255);\n"
"                      border-bottom: 2px solid transparent;\n"
"                      border-radius:8px;\n"
"                        }")
        self.reset_button_4.setObjectName("reset_button_4")
        self.gridLayout.addWidget(self.view_port_4, 1, 1, 1, 1)
        self.view_port_3 = QtWidgets.QGroupBox(self.layoutWidget)
        self.view_port_3.setObjectName("view_port_3")
        self.comp_selection_3 = QtWidgets.QComboBox(self.view_port_3)
        self.comp_selection_3.setGeometry(QtCore.QRect(310, 270, 161, 21))
        self.comp_selection_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comp_selection_3.setStyleSheet("QComboBox{\n"
"            font: 12pt \"Modern No. 20\";\n"
"            color: white;\n"
"            background-color: rgb(24,42,60);\n"
"            border: 1px solid white;\n"
"            border-radius:8px;\n"
"                        }")
        self.comp_selection_3.setObjectName("comp_selection_3")
        self.comp_selection_3.addItem("")
        self.horizontalSlider_3 = QtWidgets.QSlider(self.view_port_3)
        self.horizontalSlider_3.setGeometry(QtCore.QRect(100, 270, 201, 20))
        self.horizontalSlider_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.horizontalSlider_3.setStyleSheet("QSlider::handle:horizontal {\n"
"        background: #00aaff;  /* Blue handle */\n"
"        border: 2px solid #005f87;  /* Darker border for contrast */\n"
"        margin: -10px 0;  /* Adjust to center the handle on the groove */\n"
"        border-radius: 6px;\n"
"    }")
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setObjectName("horizontalSlider_3")
        self.horizontalSlider_3.setRange(0,100)
        self.input_image_3 = QtWidgets.QLabel(self.view_port_3)
        self.input_image_3.setGeometry(QtCore.QRect(10, 20, 270, 240))
        self.input_image_3.setStyleSheet("QLabel {\n"
"                          color: rgb(42, 66, 79);\n"
"                       border-bottom: 2px solid transparent;\n"
"                      background-color: rgb(255, 255, 255);\n"
"                       border-radius:10px;\n"
"                      border: 1px solid black;\n"
"                        }")
        self.input_image_3.setText("")
        self.input_image_3.setObjectName("input_image_3")
        self.FT_components_3 = QtWidgets.QLabel(self.view_port_3)
        self.FT_components_3.setGeometry(QtCore.QRect(290, 20, 200, 240))
        self.FT_components_3.setStyleSheet("QLabel {\n"
"                          color: rgb(42, 66, 79);\n"
"                      background-color: rgb(255, 255, 255);\n"
"                       border-radius:10px;\n"
"                        }")
        self.FT_components_3.setText("")
        self.FT_components_3.setObjectName("FT_components_3")
        self.reset_button_3 = QtWidgets.QPushButton(self.view_port_3)
        self.reset_button_3.setGeometry(QtCore.QRect(10, 270, 84, 25))
        self.reset_button_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.reset_button_3.setStyleSheet("QPushButton {\n"
"                    font: 10pt \"Rockwell\";\n"
"                      padding: 5px;\n"
"                         color: rgb(42, 66, 79);\n"
"                     background-color: rgb(255, 255, 255);\n"
"                      border-bottom: 2px solid transparent;\n"
"                      border-radius:8px;\n"
"                        }")
        self.reset_button_3.setObjectName("reset_button_3")
        self.gridLayout.addWidget(self.view_port_3, 1, 0, 1, 1)
        self.view_port_1 = QtWidgets.QGroupBox(self.layoutWidget)
        self.view_port_1.setObjectName("view_port_1")
        self.comp_selection_1 = QtWidgets.QComboBox(self.view_port_1)
        self.comp_selection_1.setGeometry(QtCore.QRect(310, 270, 161, 21))
        self.comp_selection_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comp_selection_1.setStyleSheet("QComboBox{\n"
"            font: 12pt \"Modern No. 20\";\n"
"            color: white;\n"
"            background-color: rgb(24,42,60);\n"
"            border: 1px solid white;\n"
"            border-radius:8px;\n"
"                        }")
        self.comp_selection_1.setObjectName("comp_selection_1")
        self.comp_selection_1.addItem("")
        self.horizontalSlider_1 = QtWidgets.QSlider(self.view_port_1)
        self.horizontalSlider_1.setGeometry(QtCore.QRect(100, 270, 201, 20))
        self.horizontalSlider_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.horizontalSlider_1.setStyleSheet("QSlider::handle:horizontal {\n"
"        background: #00aaff;  /* Blue handle */\n"
"        border: 2px solid #005f87;  /* Darker border for contrast */\n"
"        margin: -10px 0;  /* Adjust to center the handle on the groove */\n"
"        border-radius: 6px;\n"
"    }")
        self.horizontalSlider_1.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_1.setObjectName("horizontalSlider_1")
        self.horizontalSlider_1.setRange(0,100)
        self.input_image_1 = QtWidgets.QLabel(self.view_port_1)
        self.input_image_1.setGeometry(QtCore.QRect(10, 20, 270, 240))
        self.input_image_1.setStyleSheet("QLabel {\n"
"                          color: rgb(42, 66, 79);\n"
"                      background-color: rgb(255, 255, 255);\n"
"                       border-radius:10px;\n"
"                        }")
        self.input_image_1.setText("")
        self.input_image_1.setObjectName("input_image_1")
        self.FT_components_1 = QtWidgets.QLabel(self.view_port_1)
        self.FT_components_1.setGeometry(QtCore.QRect(290, 20, 200, 240))
        self.FT_components_1.setStyleSheet("QLabel {\n"
"                          color: rgb(42, 66, 79);\n"
"                      background-color: rgb(255, 255, 255);\n"
"                       border-radius:10px;\n"
"                        }")
        self.FT_components_1.setText("")
        self.FT_components_1.setObjectName("FT_components_1")
        self.reset_button_1 = QtWidgets.QPushButton(self.view_port_1)
        self.reset_button_1.setGeometry(QtCore.QRect(10, 270, 84, 25))
        self.reset_button_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.reset_button_1.setStyleSheet("QPushButton {\n"
"                    font: 10pt \"Rockwell\";\n"
"                      padding: 5px;\n"
"                         color: rgb(42, 66, 79);\n"
"                     background-color: rgb(255, 255, 255);\n"
"                      border-bottom: 2px solid transparent;\n"
"                      border-radius:8px;\n"
"                        }")
        self.reset_button_1.setObjectName("reset_button_1")
        self.gridLayout.addWidget(self.view_port_1, 0, 0, 1, 1)
        self.view_port_2 = QtWidgets.QGroupBox(self.layoutWidget)
        self.view_port_2.setObjectName("view_port_2")
        self.comp_selection_2 = QtWidgets.QComboBox(self.view_port_2)
        self.comp_selection_2.setGeometry(QtCore.QRect(310, 270, 161, 21))
        self.comp_selection_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comp_selection_2.setStyleSheet("QComboBox{\n"
"            font: 12pt \"Modern No. 20\";\n"
"            color: white;\n"
"            background-color: rgb(24,42,60);\n"
"            border: 1px solid white;\n"
"            border-radius:8px;\n"
"                        }")
        self.comp_selection_2.setObjectName("comp_selection_2")
        self.comp_selection_2.addItem("")
        self.horizontalSlider_2 = QtWidgets.QSlider(self.view_port_2)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(100, 270, 201, 20))
        self.horizontalSlider_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.horizontalSlider_2.setStyleSheet("QSlider::handle:horizontal {\n"
"        background: #00aaff;  /* Blue handle */\n"
"        border: 2px solid #005f87;  /* Darker border for contrast */\n"
"        margin: -10px 0;  /* Adjust to center the handle on the groove */\n"
"        border-radius: 6px;\n"
"    }")
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.horizontalSlider_2.setRange(0,100)
        self.input_image_2 = QtWidgets.QLabel(self.view_port_2)
        self.input_image_2.setGeometry(QtCore.QRect(10, 20, 270, 240))
        self.input_image_2.setStyleSheet("QLabel {\n"
"                          color: rgb(42, 66, 79);\n"
"                       border-bottom: 2px solid transparent;\n"
"                      background-color: rgb(255, 255, 255);\n"
"                       border-radius:10px;\n"
"                      border: 1px solid black;\n"
"                        }")
        self.input_image_2.setText("")
        self.input_image_2.setObjectName("input_image_2")
        self.FT_components_2 = QtWidgets.QLabel(self.view_port_2)
        self.FT_components_2.setGeometry(QtCore.QRect(290, 20, 200, 240))
        self.FT_components_2.setStyleSheet("QLabel {\n"
"                          color: rgb(42, 66, 79);\n"
"                      background-color: rgb(255, 255, 255);\n"
"                       border-radius:10px;\n"
"                        }")
        self.FT_components_2.setText("")
        self.FT_components_2.setObjectName("FT_components_2")
        self.reset_button_2 = QtWidgets.QPushButton(self.view_port_2)
        self.reset_button_2.setGeometry(QtCore.QRect(10, 270, 84, 25))
        self.reset_button_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.reset_button_2.setStyleSheet("QPushButton {\n"
"                    font: 10pt \"Rockwell\";\n"
"                      padding: 5px;\n"
"                         color: rgb(42, 66, 79);\n"
"                     background-color: rgb(255, 255, 255);\n"
"                      border-bottom: 2px solid transparent;\n"
"                      border-radius:8px;\n"
"                        }")
        self.reset_button_2.setObjectName("reset_button_2")
        self.gridLayout.addWidget(self.view_port_2, 0, 1, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(1020, 40, 251, 631))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.output_viewport_2 = QtWidgets.QGroupBox(self.layoutWidget1)
        self.output_viewport_2.setObjectName("output_viewport_2")
        self.outer_region = QtWidgets.QRadioButton(self.output_viewport_2)
        self.outer_region.setGeometry(QtCore.QRect(140, 45, 101, 19))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.region_group = QButtonGroup()

        self.outer_region.setFont(font)
        self.outer_region.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.outer_region.setObjectName("outer_region")
        self.inner_region = QtWidgets.QRadioButton(self.output_viewport_2)
        self.inner_region.setGeometry(QtCore.QRect(140, 30, 101, 19))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.inner_region.setFont(font)
        self.inner_region.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.inner_region.setStyleSheet("")
        self.inner_region.setObjectName("inner_region")
        self.none_region = QtWidgets.QRadioButton(self.output_viewport_2)
        self.none_region.setGeometry(QtCore.QRect(140, 60, 101, 19))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.region_group = QButtonGroup()
        self.none_region.setFont(font)
        self.none_region.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.none_region.setObjectName("none_region")
        self.region_group.addButton(self.inner_region)
        self.region_group.addButton(self.outer_region)
        self.region_group.addButton(self.none_region)
        self.progressBar = QtWidgets.QProgressBar(self.output_viewport_2)
        self.progressBar.setGeometry(QtCore.QRect(10, 590, 121, 21))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.outputSelectioncomboBox = QtWidgets.QComboBox(self.output_viewport_2)
        self.outputSelectioncomboBox.setGeometry(QtCore.QRect(10, 120, 231, 22))
        self.outputSelectioncomboBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.outputSelectioncomboBox.setStyleSheet("QComboBox{\n"
"            font: 12pt \"Modern No. 20\";\n"
"            color: white;\n"
"            background-color: rgb(24,42,60);\n"
"            border: 1px solid white;\n"
"            border-radius:8px;\n"
"                        }")
        self.outputSelectioncomboBox.setObjectName("outputSelectioncomboBox")
        self.outputSelectioncomboBox.addItem("")
        self.output_image_1 = QtWidgets.QLabel(self.output_viewport_2)
        self.output_image_1.setGeometry(QtCore.QRect(10, 150, 220, 200))
        self.output_image_1.setStyleSheet("QLabel {\n"
"                          color: rgb(42, 66, 79);\n"
"                       border-bottom: 2px solid transparent;\n"
"                      background-color: rgb(255, 255, 255);\n"
"                       border-radius:10px;\n"
"                      border: 1px solid black;\n"
"                        }")
        self.output_image_1.setText("")
        self.output_image_1.setObjectName("output_image_1")
        self.output_image_2 = QtWidgets.QLabel(self.output_viewport_2)
        self.output_image_2.setGeometry(QtCore.QRect(10, 360, 220, 200))
        self.output_image_2.setStyleSheet("QLabel {\n"
"                          color: rgb(42, 66, 79);\n"
"                       border-bottom: 2px solid transparent;\n"
"                      background-color: rgb(255, 255, 255);\n"
"                       border-radius:10px;\n"
"                      border: 1px solid black;\n"
"                        }")
        self.output_image_2.setText("")
        self.output_image_2.setObjectName("output_image_2")
        self.regionSelectionSlider = QtWidgets.QSlider(self.output_viewport_2)
        self.regionSelectionSlider.setGeometry(QtCore.QRect(10, 90, 231, 20))
        self.regionSelectionSlider.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.regionSelectionSlider.setStyleSheet("QSlider::handle:horizontal {\n"
"        background: #00aaff;  /* Blue handle */\n"
"        border: 2px solid #005f87;  /* Darker border for contrast */\n"
"        margin: -10px 0;  /* Adjust to center the handle on the groove */\n"
"        border-radius: 6px;\n"
"    }")
        self.regionSelectionSlider.setOrientation(QtCore.Qt.Horizontal)
        self.regionSelectionSlider.setObjectName("regionSelectionSlider")
        self.cancel_button = QtWidgets.QPushButton(self.output_viewport_2)
        self.cancel_button.setGeometry(QtCore.QRect(140, 590, 101, 31))
        self.cancel_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cancel_button.setStyleSheet("QPushButton {\n"
"                    font: 12pt \"Rockwell\";\n"
"                      padding: 3px;\n"
"                         color: rgb(42, 66, 79);\n"
"                     background-color: rgb(255, 255, 255);\n"
"                      border: 2px solid black;\n"
"                      border-radius:8px;\n"
"                        }")
        self.cancel_button.setObjectName("cancel_button")
        self.status_label = QtWidgets.QLabel(self.output_viewport_2)
        self.status_label.setGeometry(QtCore.QRect(10, 570, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Modern No. 20")
        font.setPointSize(12)
        self.status_label.setFont(font)
        self.status_label.setObjectName("status_label")
        self.ft_component_group = QButtonGroup()
        self.gridLayout_3.addWidget(self.output_viewport_2, 0, 0, 1, 1)
        self.real_imaginary = QtWidgets.QRadioButton(self.centralwidget)
        self.real_imaginary.setGeometry(QtCore.QRect(1030, 100, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.real_imaginary.setFont(font)
        self.real_imaginary.setObjectName("real_imaginary")
        self.magnitude_phase = QtWidgets.QRadioButton(self.centralwidget)
        self.magnitude_phase.setGeometry(QtCore.QRect(1030, 70, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.magnitude_phase.setFont(font)
        self.magnitude_phase.setObjectName("magnitude_phase")
        self.ft_component_group.addButton(self.magnitude_phase)
        self.ft_component_group.addButton(self.real_imaginary)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1277, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.quit_button.setText(_translate("MainWindow", "Quit Application"))
        self.title_label.setText(_translate("MainWindow", "Image Mixer"))
        self.view_port_4.setTitle(_translate("MainWindow", "View Port_3"))
        self.comp_selection_4.setItemText(0, _translate("MainWindow", "Select Component"))
        self.reset_button_4.setText(_translate("MainWindow", "Reset"))
        self.view_port_3.setTitle(_translate("MainWindow", "View Port_3"))
        self.comp_selection_3.setItemText(0, _translate("MainWindow", "Select Component"))
        self.reset_button_3.setText(_translate("MainWindow", "Reset"))
        self.view_port_1.setTitle(_translate("MainWindow", "View Port_1"))
        self.comp_selection_1.setItemText(0, _translate("MainWindow", "Select Component"))
        self.reset_button_1.setText(_translate("MainWindow", "Reset"))
        self.view_port_2.setTitle(_translate("MainWindow", "View Port_2"))
        self.comp_selection_2.setItemText(0, _translate("MainWindow", "Select Component"))
        self.reset_button_2.setText(_translate("MainWindow", "Reset"))
        self.output_viewport_2.setTitle(_translate("MainWindow", "Output Viewports"))
        self.outer_region.setText(_translate("MainWindow", "Outer Region"))
        self.inner_region.setText(_translate("MainWindow", "Inner Region"))
        self.none_region.setText(_translate("MainWindow", "None Region"))
        self.outputSelectioncomboBox.setItemText(0, _translate("MainWindow", "Select Output Viewport"))
        self.cancel_button.setText(_translate("MainWindow", "Cancel"))
        self.status_label.setText(_translate("MainWindow", "Status"))
        self.real_imaginary.setText(_translate("MainWindow", "Real / Imaginary"))
        self.magnitude_phase.setText(_translate("MainWindow", "Magnitude / Phase"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
